_target_: src.datamodules.datamodule.DataModule

model_name: ${model.model_name}
batch_size: 128
data_dir: ${data_dir}

datafiles:
    plaintext: 'http://data.statmt.org/news-commentary/v15/training-monolingual/news-commentary-v15.en.gz'

seat_data:

seed: ${seed}
num_proc: 32
num_workers: 16
